site_name: CloudFormation Stacks for Research Computing
theme:
  name: material
nav:
  - Introduction: "01-introduction.md"
  - Installation: "02-installation.md"
  - Setup: "03-setup.md"
  - Deployment: "04-deployment.md"
  - User Management: "05-user_management.md"
  - Credentials and Roles: "06-credentials_roles.md"
  - Collaborator Access: "07-collaborator_access.md"
  - EC2 Instance: "08-ec2_instance.md"
  - Addendum: "09-addendum.md"
