site_name: CloudFormation Stacks for Research Computing
theme:
  name: material
nav:
  - Introduction: "01-introduction.md"
  - Setup: "02-setup.md"
  - Deployment: "03-deployment.md"
  - User Management: "04-user_management.md"
  - Credentials and Roles: "05-credentials_roles.md"
  - Collaborator Access: "06-collaborator_access.md"
  - EC2 Instance: "07-ec2_instance.md"
  - Addendum: "99-addendum.md"
